export const SET_EVENTS_AND_RISK_EVENTS_AND_LOGICAL_OPERATORS_AND_ACTIVITIES = 'currentProject/SET_EVENTS_AND_RISK_EVENTS_AND_LOGICAL_OPERATORS_AND_ACTIVITIES'

export const CREATE_EVENT_OR_RISK_EVENT = 'currentProject/CREATE_EVENT_OR_RISK_EVENT'
export const UPDATE_EVENT_OR_RISK_EVENT = 'currentProject/UPDATE_EVENT_OR_RISK_EVENT'
export const DELETE_EVENT_OR_RISK_EVENT = 'currentProject/DELETE_EVENT_OR_RISK_EVENT'

export const CREATE_LOGICAL_OPERATOR = 'currentProject/CREATE_LOGICAL_OPERATOR'
export const UPDATE_LOGICAL_OPERATOR = 'currentProject/UPDATE_LOGICAL_OPERATOR'
export const DELETE_LOGICAL_OPERATOR = 'currentProject/DELETE_LOGICAL_OPERATOR'

export const CREATE_ACTIVITY = 'currentProject/CREATE_ACTIVITY'
export const UPDATE_ACTIVITY = 'currentProject/UPDATE_ACTIVITY'
export const DELETE_ACTIVITY = 'currentProject/DELETE_ACTIVITY'
